captainVersion: 4
services:
    $$cap_appname:
        image: lscr.io/linuxserver/duplicati:$$cap_duplicati_version
        environment:
            TZ: $$cap_tz
            PUID: $$cap_puid
            PGID: $$cap_guid
        volumes:
            - $$cap_appname-config:/config # Contains all relevant configuration files.
            - $$cap_appname-backups:/backups # Path to store local backups.
            - $$cap_sourcepath:/source # Path to source for files to backup.
        caproverExtra:
            containerHttpPort: '8200'
caproverOneClickApp:
    variables:
        - id: $$cap_tz
          label: Timezone
          description: Specify a timezone to use EG Europe/London, find yours at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
          defaultValue: Europe/Brussels

        - id: $$cap_duplicati_version
          label: Version Tag
          description: Check out their Docker page for the valid tags https://github.com/linuxserver/docker-duplicati/pkgs/container/duplicati
          defaultValue: 'version-v2.0.6.3-2.0.6.3_beta_2021-06-17'

        - id: $$cap_puid
          label: User ID
          defaultValue: '1000'
          description: User ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_guid
          label: Group ID
          defaultValue: '1000'
          description: Group ID that the process uses, run (id $user) in your instance to see the id
          validRegex: /.{1,}/

        - id: $$cap_sourcepath
          label: Path to source for files to backup.
    instructions:
        start: |-
            Duplicati works with standard protocols like FTP, SSH, WebDAV as well as popular services like Microsoft OneDrive, Amazon Cloud Drive & S3, Google Drive, box.com, Mega, hubiC and many others.
        end: |-
            ✅ Duplicati has been deployed!
            --------------------------------------------
            The webui is at http://$$cap_appname.$$cap_root_domain , create backup jobs etc via the webui, for local backups select /backups as the destination.
    displayName: Duplicati
    isOfficial: true
    description: Free backup software to store encrypted backups online For Windows, macOS and Linux.
    documentation: https://docs.linuxserver.io/images/docker-duplicati
