name: Publish Apps

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Make executeable
        run: chmod +x ./scripts/publish-from-actions.sh
      - run: npm ci && npm run publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
