name: Publish One Click Apps

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@d6e3b5539ed7e5ccd26c3459e26c7c817f4e9068 # renovate: tag=v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache .pnpm-store
              uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
            - name: Deploy github page
              run: pnpm i && pnpm run publish
              env:
                  GITHUB_TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
