name: Publish One Click Apps

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
            - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache .pnpm-store
              uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
            - name: Deploy github page
              run: pnpm i && pnpm run publish
              env:
                  GITHUB_TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
