name: Publish One Click Apps

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
            - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # tag=v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache .pnpm-store
              uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514 # tag=v3
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
            - name: Deploy github page
              run: pnpm i && pnpm run publish
              env:
                  GITHUB_TOKEN: $GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}
