name: Validate One Click Apps

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14]
        steps:
            - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache .pnpm-store
              uses: actions/cache@c64c572235d810460d0d6876e9c705ad5002b353 # renovate: tag=v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            - name: Install pnpm
              run: curl -f https://get.pnpm.io/v6.7.js | node - add --global pnpm@6
            - name: Run Validate and Formatter
              run: pnpm i && pnpm run validate_apps && pnpm run formatter
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
